services:
  - type: web
    name: renyra-backend
    runtime: docker
    region: singapore
    plan: free
    healthCheckPath: /api/v1/health
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_NAME
        value: anchor_db
      - key: JWT_EXPIRE
        value: 24
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_TYPE
        value: service_account
      - key: FIREBASE_AUTH_URI
        value: https://accounts.google.com/o/oauth2/auth
      - key: FIREBASE_TOKEN_URI
        value: https://oauth2.googleapis.com/token
      - key: FIREBASE_AUTH_PROVIDER_X509_CERT_URL
        value: https://www.googleapis.com/oauth2/v1/certs
      - key: FIREBASE_UNIVERSE_DOMAIN
        value: googleapis.com
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: FIREBASE_CLIENT_X509_CERT_URL
        sync: false
